blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://community.theia-ide.org
    about: Please ask questions on the Theia Discourse.
  - name: Create issue
    url: https://github.com/eclipse-theia/theia-e2e-test-suite/issues/new/choose
    about: Please create issues in this repository.
